Included changes from main repo - use gpick in ubuntu/pop_os instead of colorpicker (only option i could get to work)

diff --git a/canvas b/canvas
--- a/canvas
+++ b/canvas
@@ -8,13 +8,13 @@
 ## Canvas - An Imagemagick Script To Generate Wallpapers.
 
 ## TTY Colors
-R='\033[1;31m'
-G='\033[1;32m'
-Y='\033[1;33m'
-B='\033[1;34m'
-M='\033[1;35m'
-C='\033[0;36m'
-W='\033[1;37m'
+R="\033[1;31m"
+G="\033[1;32m"
+Y="\033[1;33m"
+B="\033[1;34m"
+M="\033[1;35m"
+C="\033[0;36m"
+W="\033[1;37m"
 
 ## Variables
 DIR="$HOME/Pictures/Canvas"
@@ -34,13 +34,20 @@ reset_color() {
 
 ## Preq
 preq() {
-    dependencies=(convert feh)
+    dependencies=(convert feh 'colorpicker or gpick')
     for dependency in "${dependencies[@]}"; do
-        type -p "$dependency" &>/dev/null || {
-            echo -e $R"ERROR: Could not find $G'${dependency}'$R, is it installed?" >&2
-            reset_color
-            exit 1
-        }
+		dep_options=(${dependency// or / })
+		depFound=${#dep_options[@]}
+		for curDep in "${dep_options[@]}"; do
+			type -p "$curDep" &>/dev/null || {
+				depFound=$(( depFound - 1 ))
+			}
+		done
+		if [[ "$depFound" == "0" ]]; then
+			echo -e $R"ERROR: Could not find $G'${dependency}'$R, is it installed?" >&2
+			reset_color
+			exit 1
+		fi
     done
 
 	if [[ ! -d "$DIR" ]]; then
@@ -71,7 +78,7 @@ Options:
    -b   --bilinear	Generate a bilinear(4point) gradient wallpaper
    -p   --plasma	Generate a plasma wallpaper
    -n   --nopreview	Do not show preview when image is generated 
-   -a   --autobg	Automatically set as wallpaper
+   -a   --autobg	Automatically set as wallpaper (implies -n)
    -R   --randomize	Random Options
 "
 }
@@ -136,66 +143,127 @@ set_bg() {
 }
 
 ## Show preview of generated image unless paramaters supplied tells it not
-showFeh() {
-	if [[ "$NOFEH" != "true" ]]; then
+show_feh() {
+	if [[ "$NOFEH" != "true" ]] && [[ "$AUTOBG" != "true" ]]; then
 		feh --borderless --scale-down --geometry="$PSIZE" --title="$NAME" "$DIR/$NAME" &>/dev/null &
+	fi
+}
+
+## Pick the colors
+color_picker() {
+	picker_app="colorpicker --short --one-shot"
+	type -p "colorpicker" &>/dev/null || {
+		depFound=$(( depFound - 1 ))
+	}
+	picker_app="gpick -s -o --no-newline"
+	if [[ "$SOLID" == "true" ]]; then
+		echo
+		echo -e $Y"Pick a color..."
+		COLOR=$($picker_app)
+		echo
+		echo -e $Y"Generating wallpaper with color:$G $COLOR"
+	elif [[ "$GRADIENT" == "true" ]] || [[ "$RGRADIENT" == "true" ]] || [[ "$TGRADIENT" == "true" ]]; then
+		echo
+		echo -e $Y"Pick first color..."
+		color1=$($picker_app)
+		echo -e $Y"Pick second color..."
+		color2=$($picker_app)
+		COLOR="$color1-$color2"
+		echo
+		echo -e $Y"Generating wallpaper with colors:$G $color1, $color2"
+	elif [[ "$BGRADIENT" == "true" ]]; then
+		echo
+		echo -e $Y"Pick first color..."
+		color1=$($picker_app)
+		echo -e $Y"Pick second color..."
+		color2=$($picker_app)
+		echo -e $Y"Pick third color..."
+		color3=$($picker_app)
+		echo -e $Y"Pick fourth color..."
+		color4=$($picker_app)
+		echo
+		echo -e $Y"Generating wallpaper with colors:$G $color1, $color2, $color3 & $color4"
+	fi
+}
+
+## Get colors
+get_color() {
+	echo
+	echo -ne $Y"Pick Colors or Enter Colors? (p/e):$G "
+	read ANS
+	if [[ $ANS == "p" ]] || [[ $ANS == "P" ]]; then
+		color_picker
+	else
+		if [[ "$SOLID" == "true" ]]; then	
+			echo
+			echo -ne $Y"Enter the color name or hex (eg: teal, #EBCB8B):$G "
+			read COLOR
+		elif [[ "$GRADIENT" == "true" ]] || [[ "$RGRADIENT" == "true" ]] || [[ "$TGRADIENT" == "true" ]]; then
+			echo
+			echo -ne $Y"Enter the colors name or hex (format: color1-color2):$G "
+			read COLOR
+		elif [[ "$BGRADIENT" == "true" ]]; then
+			echo
+			echo -ne $Y"Enter first color (eg: red, #EC7875):$G "
+			read color1
+			echo -ne $Y"Enter second color (eg: green, #61C766):$G "
+			read color2
+			echo -ne $Y"Enter third color (eg: yellow, #FDD835):$G "
+			read color3
+			echo -ne $Y"Enter fourth color (eg: blue, #42A5F5):$G "
+			read color4
+		fi
 	fi
 }
 
 ## Generate a solid color wallpaper
 solid() {
 	if [[ "$RANDOMIZE" == "true" ]]; then
-		getRandomColor
+		get_random_color
 		COLOR="$RCOLOR"
 	else
-		echo
-		echo -ne $Y"Enter the color name or hex (eg: teal, #EBCB8B):$G "
-		read COLOR
+		get_color
 	fi
 	convert -size "$SIZE" canvas:"$COLOR" "$DIR/$NAME"
-	showFeh
+	show_feh
 	set_bg
 }
 
 ## Generate a linear gradient wallpaper
 linear_gradient() {
 	if [[ "$RANDOMIZE" == "true" ]]; then
-		getRandomColor
+		get_random_color
 		COLOR="$RCOLOR"
 		
-		getRandomNumber "360"
+		get_random_number "360"
 		ANGLE="$RNUM"
 	else
-		echo
-		echo -ne $Y"Enter the colors name or hex (format: color1-color2):$G "
-		read COLOR
+		get_color
 		echo
 		echo -ne $Y"Enter the rotation angle (default is 0):$G "
 		read ANGLE
 	fi
 	convert -size "$SIZE" -define gradient:angle="$ANGLE" gradient:"$COLOR" "$DIR/$NAME"
-	showFeh
+	show_feh
 	set_bg
 }
 
 ## Generate a radial gradient wallpaper
 radial_gradient() {
 	if [[ "$RANDOMIZE" == "true" ]]; then
-		getRandomColor
+		get_random_color
 		COLOR1="$RCOLOR"
-		getRandomColor
+		get_random_color
 		COLOR="$COLOR1-$RCOLOR"
 		
-		getRandomNumber "360"
+		get_random_number "360"
 		ANGLE="$RNUM"
 
 		getRandomShape
 		SHAPE="$RSHAPE"
 	else
 		SHAPE=maximum
-		echo
-		echo -ne $Y"Enter the colors name or hex (format: color1-color2):$G "
-		read COLOR
+		get_color
 		echo
 		echo -ne $Y"Shape? (diagonal, ellipse, maximum, minimum):$G "
 		read SHAPE
@@ -204,61 +272,52 @@ radial_gradient() {
 		read ANGLE
 	fi
 	convert -size "$SIZE" -define gradient:extent="$SHAPE" -define gradient:angle="$ANGLE" radial-gradient:"$COLOR" "$DIR/$NAME"
-	showFeh
+	show_feh
 	set_bg
 }
 
 ## Generate a twisted gradient wallpaper
 twisted_gradient() {
 	if [[ "$RANDOMIZE" == "true" ]]; then
-		getRandomColor
+		get_random_color
 		COLOR1="$RCOLOR"
-		getRandomColor
+		get_random_color
 		COLOR="$COLOR1-$RCOLOR"
 		
-		getRandomNumber "500"
+		get_random_number "500"
 		TWIST="$RNUM"
 	else
-		echo
-		echo -ne $Y"Enter the colors name or hex (format: color1-color2):$G "
-		read COLOR
+		get_color
 		echo
 		echo -ne $Y"Enter the twisting amount (maximum 500):$G "
 		read TWIST
 	fi
 	convert -size "$SIZE" gradient:"$COLOR" -swirl "$TWIST" "$DIR/$NAME"
-	showFeh
+	show_feh
 	set_bg
 }
 
 ## Generate a 4 point gradient wallpaper
 bilinear_gradient() {
 	if [[ "$RANDOMIZE" == "true" ]]; then
-		getRandomColor
+		get_random_color
 		color1="$RCOLOR"
-		getRandomColor
+		get_random_color
 		color2="$RCOLOR"
-		getRandomColor
+		get_random_color
 		color3="$RCOLOR"
-		getRandomColor
+		get_random_color
 		color4="$RCOLOR"
 		
-		getRandomNumber "2"
+		get_random_number "2"
 		if [[ "$RNUM" == "1" ]]; then
 			ANS="s"
 		else
 			ANS="r"
 		fi
 	else
+		get_color
 		echo
-		echo -ne $Y"Enter first color (eg: red, #EC7875):$G "
-		read color1
-		echo -ne $Y"Enter second color (eg: green, #61C766):$G "
-		read color2
-		echo -ne $Y"Enter third color (eg: yellow, #FDD835):$G "
-		read color3
-		echo -ne $Y"Enter fourth color (eg: blue, #42A5F5):$G "
-		read color4
 		echo -ne $Y"Smooth or Regular? (s/r):$G "
 		read ANS
 	fi
@@ -267,24 +326,24 @@ bilinear_gradient() {
 	else
 		convert \( xc:"$color1" xc:"$color2" +append \) \( xc:"$color3" xc:"$color4" +append \) -append -filter triangle -resize "$SIZE"\! "$DIR/$NAME"
 	fi
-	showFeh
+	show_feh
 	set_bg
 }
 
 ## Generate a plasma wallpaper
 plasma() {
 	if [[ "$RANDOMIZE" == "true" ]]; then
-		getRandomNumber "3"
+		get_random_number "3"
 
 		if [[ "$RNUM" == "1" ]]; then
 			ANS="r"
 		elif [[ "$RNUM" == "2" ]]; then
 			ANS="t"
-			getRandomNumber "500"
+			get_random_number "500"
 			TWIST="$RNUM"
 		else
 			ANS="c"
-			getRandomColor
+			get_random_color
 			COLOR="$RCOLOR"
 		fi
 	else
@@ -309,14 +368,14 @@ plasma() {
 		fi
 		convert -size "$SIZE" plasma:"$COLOR" "$DIR/$NAME"
 	fi
-	showFeh
+	show_feh
 	set_bg
 }
 
 ## Generate a random, multi-colored blured/gradient wallpaper
 blured_noise() {
 	if [[ "$RANDOMIZE" == "true" ]]; then
-		getRandomNumber "30"
+		get_random_number "30"
 		BLUR="$RNUM"
 	else
 		echo
@@ -325,21 +384,21 @@ blured_noise() {
 	fi
 	convert -size "100x56" xc: +noise Random "/tmp/noise.png"
 	convert "/tmp/noise.png" -virtual-pixel tile -blur 0x"$BLUR" -auto-level -resize "$SIZE" "$DIR/$NAME"	
-	showFeh
+	show_feh
 	set_bg
 }
 
 ## Generate random number lower than giver parameter
-getRandomNumber() {
+get_random_number() {
 	RNUM=$(( ($RANDOM % $1) + 1 ))
 }
 
 ## Generate random color
-getRandomColor() {
+get_random_color() {
 	RCOLOR="#"
 	for i in 1 2 3 4 5 6
 	do
-		getRandomNumber "16"
+		get_random_number "16"
 		case $RNUM in
 			"1") NEXTDIGIT="1";;
 			"2") NEXTDIGIT="2";;
@@ -364,7 +423,7 @@ getRandomColor() {
 
 ## Generate random shape option
 getRandomShape() {
-	getRandomNumber "4"
+	get_random_number "4"
 	case $RNUM in
 		"1") RSHAPE="diagonal";;
 		"2") RSHAPE="ellipse";;
@@ -375,7 +434,7 @@ getRandomShape() {
 
 ## Generate random wallpaper
 randomize() {
-	getRandomNumber "7"
+	get_random_number "7"
 	case $RNUM in
 		"1") solid;;
 		"2") linear_gradient;;
